#!/bin/zsh

cpanm                                                               \
   App::Nopaste                                                     \
   Carp::Always                                                     \
   Catalyst::Action::RenderView                                     \
   Catalyst::Action::REST                                           \
   Catalyst::ActionRole::PseudoCache                                \
   Catalyst::Authentication::Store::DBIx::Class                     \
   Catalyst::Controller::Accessors                                  \
   Catalyst::Devel                                                  \
   Catalyst::Model::DBIC::Schema                                    \
   Catalyst::Plugin::Authentication                                 \
   Catalyst::Plugin::Cache                                          \
   Catalyst::Plugin::ConfigLoader                                   \
   Catalyst::Plugin::Session                                        \
   Catalyst::Plugin::Session::State::Cookie                         \
   Catalyst::Plugin::Session::Store::DBIC                           \
   Catalyst::Plugin::Static::Simple                                 \
   Catalyst::Runtime                                                \
   Catalyst::TraitFor::Controller::DBIC::DoesPaging                 \
   Catalyst::TraitFor::Controller::DoesExtPaging                    \
   Catalyst::View::JavaScript::Minifier::XS                         \
   Catalyst::View::Jemplate                                         \
   Catalyst::View::JSON                                             \
   Catalyst::View::TT                                               \
   Check::ISA                                                       \
   Crypt::Eksblowfish                                               \
   Data::UUID                                                       \
   DateTime::Format::MSSQL                                          \
   DBIx::Class                                                      \
   DBIx::Class::Candy                                               \
   DBIx::Class::DeploymentHandler                                   \
   DBIx::Class::Helpers                                             \
   DBIx::Class::Schema::Loader                                      \
   DBIx::Class::TimeStamp                                           \
   Devel::Cover                                                     \
   Dist::Zilla                                                      \
   Dist::Zilla::PluginBundle::Basic                                 \
   Dist::Zilla::PluginBundle::Git                                   \
   Dist::Zilla::Plugin::PodWeaver                                   \
   Dist::Zilla::Plugin::ReadmeFromPod                               \
   Email::MIME::Kit                                                 \
   Email::MIME::Kit::Renderer::TT                                   \
   Exception::Reporter                                              \
   Exception::Reporter::Summarizer::Catalyst                        \
   ExtUtils::MakeMaker                                              \
   JSON::XS                                                         \
   Log::Contextual                                                  \
   Log::Log4perl                                                    \
   Log::Log4perl::Appender::DBIx::Class                             \
   Log::Sprintf                                                     \
   Log::Structured                                                  \
   MIME::Base64                                                     \
   Module::Install                                                  \
   Moo                                                              \
   Moose                                                            \
   namespace::clean                                                 \
   Perl::Tidy                                                       \
   rlib                                                             \
   String::Random                                                   \
   Sub::Exporter                                                    \
   syntax                                                           \
   Syntax::Feature::Method                                          \
   Syntax::Keyword::Junction                                        \
   Test::More                                                       \
   Test::WWW::Mechanize::PSGI                                       \
   Text::CSV                                                        \
   Text::CSV_XS                                                     \
   Time::Duration                                                   \
   Time::Duration::Parse                                            \
   XML::Simple
