#!/bin/dash

if [ ! -d ~/.local/share/applications ]; then
   exit
fi

for x in bible mid bugzid; do
   xdg-mime install ./xdg/frew-$x.desktop
   xdg-mime default frew-$x.desktop x-scheme-handler/$x
   cp ./xdg/frew-$x.desktop ~/.local/share/applications
done

# vim: ft=sh
