#!/bin/bash

apt-get --no-install-recommends install \
   aptitude                             \
   asciidoc                             \
   autoconf                             \
   automake                             \
   awesome                              \
   awesome-extra                        \
   build-essential                      \
   clementine                           \
   curl                                 \
   dstat                                \
   dtach                                \
   fail2ban                             \
   firefox                              \
   git-annex                            \
   gnome-power-manager                  \
   gnome-system-monitor                 \
   gnupg-agent                          \
   gtk2-engines                         \
   gxmessage                            \
   inotify-tools                        \
   keepassx                             \
   lastfm                               \
   libcurl4-openssl-dev                 \
   libgmime-2.6-dev                     \
   libgpgme11-dev                       \
   libncursesw5-dev                     \
   libnotmuch-dev                       \
   libpam0g-dev                         \
   libtalloc-dev                        \
   libtokyocabinet-dev                  \
   libtool                              \
   libxapian-dev                        \
   lynx                                 \
   mosh                                 \
   msmtp                                \
   notmuch                              \
   notmuch-mutt                         \
   offlineimap                          \
   openssh-client                       \
   openssh-server                       \
   openvpn                              \
   pcmanfm                              \
   rdesktop                             \
   remind                               \
   suckless-tools                       \
   tcl                                  \
   terminator                           \
   tk                                   \
   tk8.5                                \
   tkremind                             \
   tmux                                 \
   ttf-ancient-fonts                    \
   unattended-upgrades                  \
   vim                                  \
   vim-gnome                            \
   xclip                                \
   xdotool                              \
   xfonts-terminus                      \
   xfonts-terminus-oblique              \
   xmlto                                \
   xscreensaver                         \
   xsltproc                             \
   zsh

