#!/bin/sh

set -e

touch ~/.frewmbot-local ~/.frewmbot-maintained

sudo apt-add-repository ppa:git-core/ppa
wget -qO- https://updates.signal.org/desktop/apt/keys.asc |
        gpg --dearmor |
        sudo tee /etc/apt/trusted.gpg.d/signal.gpg
echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" |
        sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
sudo apt update
sudo apt install git signal-desktop
mkdir -p ~/code
git clone https://github.com/frioux/dotfiles ~/code/dotfiles
cd ~/code/dotfiles
sudo ./packages.sh
./install.sh
cat sysctl.conf | sudo tee -a /etc/sysctl.conf
sudo cp xsession.desktop /usr/share/xsessions/xsession.desktop
sudo cp random.rules /etc/udev/rules.d/71-disable-random-entropy-estimation.rules
sudo cp ./pm/* /etc/pm/sleep.d/
sudo cp ./rc.local /etc/rc.local
sudo chown root:root /etc/rc.local
sudo chmod 755 /etc/rc.local

# || true is because this fails in github actions
chsh -s /bin/zsh || true
