#!/bin/dash

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
message_count="$(postqueue -j | wc -l)"
#if [ $message_count -gt 0 ]; then
   notify-send -u critical "Emails unsent: $message_count"
#fi
