#!/bin/zsh

set -e

younger-than "$TMPDIR/cal" m 1h && exit

out=$(gcalcli --calendar fREW agenda "$(date)" "$(date --date=@$(( $(date +%s) + 8 * 60 * 60 )) )")

if [[ "$out" =~ "No Events Found" ]]; then
   echo "" > $TMPDIR/cal
   exit
fi

echo "$out" |
   cut -b 13- |
   skip 1 > $TMPDIR/cal.tmp && mv $TMPDIR/cal.tmp $TMPDIR/cal
