#!/usr/bin/perl

use strict;
use warnings;

my @command = (
   $ARGV[0],
   qw( sudo -Hu ), (getpwuid $>)[0],
   'env', 'TERM=linux',
          'PAGER=less -M',
          'STARTERVIEW=/var/starterview',
   @ARGV[1 ..  $#ARGV],
);
exec '_execroot', @command;
