#!/bin/dash

exec _execroot \
   chown -R \
   $1 \
   $(_execroot perl -e'print join q( ), glob(q(/tmp/TT*_cache-0))') \
   /var/starterview/app/view/static/assembled \
   /home/frew/profiling \
   /vol/log/www \
   /var/log/apache2/zr-perl/ \
   /home/frew/log
