#!/usr/bin/env perl

use 5.14.0;
use warnings;

die "Usage: $0 Foo::Bar 'A->new'\n" unless @ARGV >= 2;

my $debug = 1;

unless ($ARGV[0]) {
   $debug = 0;
   shift @ARGV;
}
my $script = pop @ARGV;
my (@modules) = @ARGV;

my $alias = 'A';
for (@modules) {
   warn "$_ → $alias\n" if $debug;
   $_ = "-Maliased=$_,$alias";
   $alias++;
}

exec 'run-d',
   'perl',
      '-MStarterView::Bootstrap',
      @modules,
      "-E$script"
