#!/usr/bin/env perl

use 5.22.0;
use warnings;
use String::ShellQuote 'shell_quote';

my $ssh_args = $ENV{SSH_ARGS} // '-q';

exec 'ssh', '-t', ($ssh_args ? ($ssh_args) : ()), $ENV{WWW},
   'bash', '-c', shell_quote(
      (join '', map qq($_; ),
         'cd /var/starterview',
         'export PATH="$PATH:/var/starterview/bin"',
         'export STARTERVIEW=/var/starterview',
         'export TERM=linux',
         'export PAGER=less',
         'export ZR_SECRET_PATH=/var/starterview/passwords',
         "export LESS=$ENV{LESS}",
      ) . shell_quote(@ARGV)
   )
