#!/bin/sh

set -e

. "$HOME/.env"

older-than "$HOME/zr-addresses" a 24h

TMP="$HOME/zr-addresses-built.tmp"

export NOTMUCH_CONFIG="$HOME/.zr-notmuch-config"

# reaches out to the internet, likely to fail, so don't pipe
zr-goobook query '' > $TMP

< $TMP grep -v '^	' | sort | sponge $TMP

perl -MJSON - <<'PERL' |
use 5.20.0;
my $pn = 'prefName';
sub l {
  my $dn = "$_->{firstName} $_->{lastName}";
  $dn = "($_->{$pn}) $dn"
     if $_->{$pn} && index(fc "$dn", fc $_->{$pn}) == -1;
  join "\t", $_->{email}, $dn, $_->{department}
}
open my $fh, "<", "$ENV{HOME}/Dropbox/zr/bamboo/bamboo.js";
my $json = do { local $/; <$fh> };
my $data = decode_json($json);
say l($_) for $data->{employees}->@*
PERL
   grep -v '^	' | sort >> $TMP

notmuch address date:..2099-12-13 |
   addrspec-to-tabs |
   grep -v '^[dk]+' |
   sort >> $TMP
< $TMP addrs '/home/frew/var/zr-mail/gmail.Sent_Mail/cur/*' | sponge $TMP
mv $TMP "$HOME/zr-addresses"
